export const CLINIC_DEPARTMENTS = [
  { name: 'Psychiatry', description: 'Mental health, clinical psychiatry & behavioral wellness', icon: 'Brain' },
  { name: 'Surgery', description: 'General, laparoscopic & minimally invasive surgery', icon: 'Activity' },
  { name: 'Pediatrics', description: 'Pediatric care, hematology, oncology & child health', icon: 'Baby' },
  { name: 'Dermatology', description: 'Skin, venereology, allergy care & laser treatments', icon: 'Sparkles' },
  { name: 'Cardiology', description: 'Heart, blood vessels, and cardiovascular health', icon: 'HeartPulse' },
  { name: 'General Medicine', description: 'Comprehensive adult health, routine exams & preventive care', icon: 'Stethoscope' },
];

export const CLINIC_DOCTORS = [
  {
    _id: 'doc_azizul_01',
    id: 'doc_azizul_01',
    name: 'Dr. Md. Azizul Islam',
    email: 'dr.azizul@hospital.com',
    phoneNumber: '+8801712637265, +8801919637265',
    specialization: 'Senior Consultant, Psychiatry',
    department: 'Psychiatry',
    qualification: 'MBBS, FCPS, FRCP (UK), FACP (USA)',
    experience: 20,
    consultationFee: 0,
    approvalStatus: 'approved',
    bio: 'Senior Consultant Psychiatrist specializing in mental health, clinical psychiatry, cognitive care, and behavioral wellness. Chamber Phone: 0721-750742-3/111.',
    avatar: '/doctor-images/dr_azizul.jpg',
    clinicAddress: 'Rajshahi Medical College Hospital / Chamber',
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday'],
    startTime: '09:00 AM',
    endTime: '08:30 PM',
    breakStartTime: '01:30 PM',
    breakEndTime: '02:30 PM',
    slotDuration: 30,
  },
  {
    _id: 'doc_moksed_02',
    id: 'doc_moksed_02',
    name: 'Prof. Dr. Md. Moksed Ali Bosunia',
    email: 'dr.moksed@hospital.com',
    phoneNumber: '01915997662',
    specialization: 'General & Laparoscopic Surgery',
    department: 'Surgery',
    qualification: 'MBBS, FCPS (Surgery)',
    experience: 22,
    consultationFee: 0,
    approvalStatus: 'approved',
    bio: 'Professor & Senior Specialist in General Surgery, Laparoscopic Procedures, and Advanced Surgical Care.',
    avatar: '/doctor-images/dr_moksed.jpg',
    clinicAddress: 'Rajshahi / City Medical Center, Surgical Wing',
    days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    startTime: '09:00 AM',
    endTime: '08:30 PM',
    breakStartTime: '01:30 PM',
    breakEndTime: '02:30 PM',
    slotDuration: 30,
  },
  {
    _id: 'doc_farida_03',
    id: 'doc_farida_03',
    name: 'Dr. Farida Yeasmin',
    email: 'dr.farida@hospital.com',
    phoneNumber: '01974254004',
    specialization: 'Pediatric Hematology & Oncology',
    department: 'Pediatrics',
    qualification: 'MBBS, FCPS (Pediatrics)',
    experience: 14,
    consultationFee: 0,
    approvalStatus: 'approved',
    bio: 'Dedicated Specialist in Child Health, Pediatric Hematology, and Oncology providing gentle, comprehensive care for children and infants.',
    avatar: '/doctor-images/dr_farida.jpg',
    clinicAddress: 'City Medical Center, Pediatrics Pavilion, Room 204',
    days: ['Tuesday', 'Wednesday', 'Thursday', 'Saturday', 'Sunday'],
    startTime: '09:00 AM',
    endTime: '08:30 PM',
    breakStartTime: '01:30 PM',
    breakEndTime: '02:30 PM',
    slotDuration: 30,
  },
  {
    _id: 'doc_farhana_04',
    id: 'doc_farhana_04',
    name: 'Dr. Farhana Rahman',
    email: 'dr.farhana@hospital.com',
    phoneNumber: '01715204378',
    specialization: 'Dermatology & Venereology',
    department: 'Dermatology',
    qualification: 'MBBS, MD (Dermatology & Venereology)',
    experience: 10,
    consultationFee: 0,
    approvalStatus: 'approved',
    bio: 'Expert Consultant handling clinical dermatology, venereology, skin allergies, acne management, and modern aesthetic care.',
    avatar: '/doctor-images/dr_farhana.jpg',
    clinicAddress: 'City Medical Center, Dermatology Suite 302',
    days: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
    startTime: '09:00 AM',
    endTime: '08:30 PM',
    breakStartTime: '01:30 PM',
    breakEndTime: '02:30 PM',
    slotDuration: 30,
  },
];
